### ISSUE TITLE
Do we have Grafana dashboard?

### ISSUE THREAD

**Issue by polarnik** [perfana/gatling-to-influxdb#2]
Hello! Thanks for you project. It is awesome.

Gatling team has removed a graphite/influx output from the community version. Your project is a great opportunity for Gatling community users.

Do we have Grafana dashboard? Gatling Grafana dashboard

It is a duplicate of : https://github.com/perfana/x2i/issues/1

**Comment by ghost** [comment]
Hi @polarnik, thanks for your request. I will close this issue as we continue with the x2i project in the other repo. This repo will be closed/archived.
